sudo: required
services:
  - docker

language: python

matrix:
  include:

    # PYTHON VERSIONS
    - python: '3.6'
      env: TOXENV=py36

    # META
    - python: '3.6'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=pylint
    - python: '3.6'
      env: TOXENV=mypy

    - python: '3.6'
      env: TOXENV=build-pex

install:
  - travis_retry pip install tox

script: tox -v

after_success:
  - test $TOXENV = "py36" && tox -e codecov
