FROM xsteadfastx/tox-python

RUN set -ex \
 && apt-get update \
 && apt-get install -y \
        libjpeg9-dev \
 && rm -rf /var/lib/apt/lists \
 && pip install \
        pex \
        pipenv \
 && pip3.6 install wheel

WORKDIR /data

CMD tools/build-pex.sh
